spring:
  application:
    name: oauth
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1728808662-290uub8g3297adv361evhjbfcerm5d6o.apps.googleusercontent.com
            client-secret: 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
            scope: email,profile
          naver:
            client-id: PEksiEnJkvWvsurqmQeC
            client-secret: lyu6VVQBS3
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response